version: '2'
services:
  php:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    volumes_from:
    - source
    ports:
    - '${DOCKER_PORT_PHP}:9000'
    links:
    - mysql
    - memcached
    networks:
    - bitrix
    restart: always
  nginx:
    build: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
    - source
    volumes_from:
    - source
    volumes:
#    - ./docker/certbot/conf:/etc/letsencrypt
#    - ./docker/certbot/www:/var/www/certbot
    - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#    - ./docker/nginx/conf/seo.conf:/etc/nginx/seo.conf
    - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf
    ports:
    - '${DOCKER_PORT_HTTP}:80'
#    - '443:443'
    links:
    - php
    networks:
    - bitrix
    restart: always
  source:
    image: alpine:latest
    container_name: ${PROJECT_NAME}-source
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./data/mysql:/var/lib/mysql
    - ./data/memcached:/var/lib/memcached
    - ./:/var/www/bitrix
    networks:
    - bitrix
  mysql:
    build: ./docker/db
    container_name: ${PROJECT_NAME}-mysql
    volumes_from:
    - source
    ports:
    - '${DOCKER_PORT_MYSQL}:3306'
    environment:
      MYSQL_DATABASE: ${BX_MYSQL_DATABASE}
      MYSQL_USER: ${BX_MYSQL_USER}
      MYSQL_PASSWORD: ${BX_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    command: mysqld --sql-mode=""
    networks:
    - bitrix
    restart: always
  memcached:
    image: memcached:1.5-alpine
    container_name: ${PROJECT_NAME}-memcached
    volumes_from:
    - source
    ports:
    - '${DOCKER_PORT_MEMCACHED}:11211'
    networks:
    - bitrix
    restart: always

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET}